# Generated by Django 4.0.2 on 2022-03-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomidations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of airport ')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='area name')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('auther', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='blogs')),
                ('summary', models.TextField(blank=True)),
                ('sub_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name to this dining')),
                ('name', models.CharField(max_length=50, verbose_name='Dining Name')),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name=' name  unique to specific hotel')),
                ('title', models.CharField(max_length=30)),
                ('price_dec', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('location', models.URLField(verbose_name='Location')),
                ('accomidition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.accomidations')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.areas')),
                ('dining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dining')),
                ('features', models.ManyToManyField(blank=True, to='home.Features')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name specific to offer')),
                ('main_screen', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='offer name')),
                ('summary', models.TextField(blank=True)),
                ('feature', models.TextField(blank=True)),
                ('rooms', models.TextField(blank=True)),
                ('validity', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='offer_image/')),
                ('from_price', models.IntegerField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.airports')),
                ('hotel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel_infos')),
                ('hotel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hotel_types')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, null=True)),
                ('sub', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name to this dining')),
                ('name', models.CharField(max_length=50, verbose_name='Property HighLights Name')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='region name')),
            ],
        ),
        migrations.CreateModel(
            name='Situationsal_Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('per', models.CharField(choices=[('one', 'Person'), ('couple', 'Couple'), ('family', 'Family')], max_length=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.offers')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='travel class')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email_id', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('adults', models.IntegerField(verbose_name='Adults')),
                ('children', models.IntegerField(verbose_name='children')),
                ('date_of_travel', models.DateField(verbose_name='Date of Travel')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.airports', verbose_name='Departure Airport')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.titles', verbose_name='Title')),
                ('travel_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.travel_classes', verbose_name='Travel Class')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name to this dining')),
                ('name', models.CharField(max_length=50, verbose_name='Property sub Name')),
                ('summary', models.TimeField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='property')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/')),
                ('hotel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel_infos')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='points',
            field=models.ManyToManyField(to='home.Points'),
        ),
        migrations.CreateModel(
            name='Dining_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='rooms')),
                ('cuisine', models.TextField(blank=True)),
                ('setting', models.TextField(blank=True)),
                ('dress_code', models.TextField(blank=True)),
                ('childrens', models.TextField(blank=True)),
                ('vegetarian', models.TextField(blank=True)),
                ('reservation', models.TextField(blank=True)),
                ('dining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dining')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regions', verbose_name='of region'),
        ),
        migrations.AddField(
            model_name='airports',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.areas', verbose_name='in area'),
        ),
        migrations.CreateModel(
            name='Accomidations_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='unique rooms')),
                ('image', models.ImageField(null=True, upload_to='assests/rooms')),
                ('name', models.CharField(max_length=50, verbose_name='Room name')),
                ('rooms', models.IntegerField(blank=True, verbose_name='no of rooms')),
                ('room_view', models.CharField(blank=True, max_length=50)),
                ('facilities', models.TextField(blank=True)),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.accomidations', verbose_name='Accomidation')),
            ],
        ),
    ]
