# Generated by Django 4.0.2 on 2022-03-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quote_offer_alter_accomidations_sub_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_infos',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='self_id',
            field=models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name to this property'),
        ),
        migrations.AlterField(
            model_name='property_sub',
            name='self_id',
            field=models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='name to this property_sub'),
        ),
        migrations.AlterField(
            model_name='property_sub',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
