# Generated by Django 4.0.2 on 2022-03-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotel_infos_property_alter_property_self_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_infos',
            old_name='accomidition',
            new_name='accomidation',
        ),
    ]
