# Generated by Django 4.0.2 on 2022-03-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_accomidition_hotel_infos_accomidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomidations_sub',
            old_name='accomodation',
            new_name='accomidation',
        ),
    ]
