# Generated by Django 4.0.2 on 2022-03-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_accomidations_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='hotel_info',
            new_name='hotel',
        ),
    ]
