# Generated by Django 4.0.2 on 2022-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_travels_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
