# Generated by Django 4.0.2 on 2022-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_travels_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name=0)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='phone_no',
            field=models.CharField(max_length=15, null=True, verbose_name='phone_no'),
        ),
        migrations.AddField(
            model_name='quote',
            name='time',
            field=models.TimeField(auto_created=True, null=True),
        ),
    ]
