# Generated by Django 4.0.2 on 2022-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_quote_first_name_remove_quote_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='budget',
            field=models.IntegerField(null=True, verbose_name='budget'),
        ),
    ]
