# Generated by Django 4.0.2 on 2022-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
