# Generated by Django 4.0.2 on 2022-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_offers_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_infos',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
    ]
