# Generated by Django 4.0.2 on 2022-03-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_budgets_remove_quote_date_of_travel_quote_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining_sub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
    ]
