# Generated by Django 4.0.2 on 2022-03-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_dining_sub_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='currency',
            field=models.CharField(default='$', max_length=50),
        ),
        migrations.AddField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='home.countries', verbose_name='country'),
        ),
    ]
